version: '2'
services:
  app:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: python-app-container
    ports: 
      # make incoming and outgoing ports similar for brevity
      - ${APP_PORT}:${APP_PORT}
    environment:
      ENV: ${ENV}
    network_mode: host
    volumes:
      - ./api:/app/api
      - ./migrations:/app/migrations
