version: '2'
services:
  app:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: python-app-container
    ports: 
      # make host and container ports similar for brevity
      - ${APP_PORT}:${APP_PORT}
    environment:
      ENV: ${ENV}
    volumes:
      - ./api:/app/api
      - ./migrations:/app/migrations
    depends_on:
      - database
  database:
    image: postgres:9.5
    container_name: python-app-database-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: python_api
    ports:
      - "${POSTGRES_PORT}:5432"
