version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    container_name: messenger-container
    depends_on:
      - database
    environment:
      ENV: ${ENV}
    ports: 
      # make host and container ports similar for brevity
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./api:/app/api
      - ./migrations:/app/migrations
  database:
    container_name: messenger-database-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    image: postgres:9.5
